# Generated by Django 4.1.7 on 2023-03-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_product_id_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='session',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product_qty',
            new_name='quantity',
        ),
    ]
