# Generated by Django 4.1.7 on 2023-03-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_rename_session_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='id',
        ),
    ]
