# Generated by Django 4.1.7 on 2023-03-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_rename_session_id_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='session_id',
        ),
    ]
