# Generated by Django 4.1.7 on 2023-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_cartitem_quantity_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestemp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
